/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Cart: typeof import('./src/components/Cart.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ProductList: typeof import('./src/components/ProductList.vue')['default']
    ProductoList: typeof import('./src/components/ProductList.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RegistroCliente: typeof import('./src/components/RegistroCliente.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
